version: "3.9"

services:
  flask_app:
    container_name: "web"
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    links:
      - mysql
    depends_on:
      - mysql
    expose:
      - 5000
    restart: on-failure
  mysql:
    container_name: "flask_db"
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: gf637
      MYSQL_DATABASE: flask
    # ports:
    #   - "3306:3306"